FROM node:17-alpine3.14

WORKDIR /app

COPY package*.json /app/

RUN npm install

COPY . /app

RUN npm run build:prod

EXPOSE 8000

# ADD ./start.sh /app
# RUN chmod +x ./start.sh
CMD ["npm", "run", "start:build:prod"]